# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x04news\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x01\n\x05Video\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\ntranscript\x18\x03 \x01(\t\x12$\n\x07\x63hannel\x18\x04 \x01(\x0b\x32\x13.news.Video.Channel\x12\x34\n\x10publication_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x1a$\n\x07\x43hannel\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEO']._serialized_start=55
  _globals['_VIDEO']._serialized_end=258
  _globals['_VIDEO_CHANNEL']._serialized_start=222
  _globals['_VIDEO_CHANNEL']._serialized_end=258
# @@protoc_insertion_point(module_scope)
