# Generated by Django 5.0.3 on 2024-04-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"managed": True, "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="channel",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="category",
            table="Category",
        ),
        migrations.AlterModelTable(
            name="channel",
            table="channel",
        ),
        migrations.AlterModelTable(
            name="video",
            table="Video",
        ),
    ]
