# Generated by Django 5.0.3 on 2024-04-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_category_options_alter_channel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="video",
            table="video",
        ),
    ]
