# Generated by Django 5.0.3 on 2024-04-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_category_table_alter_video_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
